### ISSUE TITLE
Tiles momentarily grayed-out when expanding notification shade

### ISSUE THREAD

**Issue by e-t-l** [CasperVerswijvelt/Better-Internet-Tiles#20]
As you can see in the screenshot below, occasionally when I swipe down the status bar, the tiles are grayed-out, as if they were disabled. This only lasts a second or less before they become active and appear as expected. This happens despite Shizuku already running. 

It also does not happen EVERY time I expand the shade; it seems to only happen if I haven't expanded the shade for a while. (In other words, if I swipe down, see the tiles are momentarily grayed-out, swipe it closed, then swipe down to open it again a minute later, the tiles will still be active, NOT grayed-out.) So, it seems almost as if the app is "waking up" after the tiles have not been viewed for a while. 

This occurs even when the app is exempted from battery optimization, so I'm guessing it might have something to do with background service management or memory usage?

![Screenshot_20230209-211559](https://user-images.githubusercontent.com/40775958/218014682-efce75d9-6f07-49e1-b89c-1b7dff447083.png)

**Comment by CasperVerswijvelt** [comment]
This is because the tiles are running in [non-active mode](https://developer.android.com/develop/ui/views/quicksettings-tiles#non-active_mode), which means that the tiles only get bound when the quick settings are actually open, so when the user opens the quick settings, the tile still needs to do some stuff before the state is updated, which is what you are seeing

I could look into what needs to be done if we were to switch to [active mode](https://developer.android.com/develop/ui/views/quicksettings-tiles#active_mode_recommended), which I hink would fix this issue

**Comment by CasperVerswijvelt** [comment]
See https://github.com/CasperVerswijvelt/Better-Internet-Tiles/issues/1#issuecomment-2016875524

In the 3.0.0 beta's the tiles now use active mode
