### ISSUE TITLE
Specify it needs root access on Fdroid description

### ISSUE THREAD

**Issue by Cwpute** [CasperVerswijvelt/Better-Internet-Tiles#29]
While it is stated in the app and on the main website, if you are to consult this app's details on the Fdroid app, this "detail" does not appear.

This is important because people with unrooted device (hi👋) will not be able to use this app, so a download is unnecessary.

**Comment by CasperVerswijvelt** [comment]
You can still use the app without root using Shizuku though

**Comment by Cwpute** [comment]
Yes but that in itself is a big hurdle not many people will want to cross, or are able to cross.
If Shizuku can help circumvent this, fine, but it should be stated as would, so that people they'd need either a rooted device or have Shizuku set up and working.

**Comment by CasperVerswijvelt** [comment]
I understand that setting up Shizuku can be a hurdle to some people, that's why it's stated in the first line of the description that either root or Shizuku is a requirement
https://github.com/CasperVerswijvelt/Better-Internet-Tiles/blob/e37d78d27dc15e4cb1665a2bcb8f880e222a900e/fastlane/metadata/android/en-US/full_description.txt#L1

**Comment by Cwpute** [comment]
Wha… 😳
Sorry, i think i was blind that day. There *is* a statement about root access and all.
I will this issue.
