### ISSUE TITLE
Android 15 beta: Toggle works but is not visible.

### ISSUE THREAD

**Issue by CookieXD** [CasperVerswijvelt/Better-Internet-Tiles#42]
Pixel 7 Pro, Android 15 AP31.240617.009 (and all older Android 15 builds)
Tried with root and Shizuku.

WiFi and Bluetooth tiles toggle it successfully but no change is visible in the quick settings panel. It is visible in the app and when I toggle it with the app instead of the quick settings tile.

Is this an Android beta bug or does the App needs adjustments?

**Comment by leifalbor** [comment]
Same issue for me, same device and build. Happy to provide logcat on request.

**Comment by CasperVerswijvelt** [comment]
Which app version are you using? The latest stable (2.6.1) or a 3.0.0 beta build?
Could you maybe provide a video of the bug, because I'm not sure if I fully understand it correctly?

I have not tested the app on Android 15 so it could be that there are some breaking changes that I have to check

**Comment by CookieXD** [comment]
I am using version version 3.0.0-beta.2-playstore
Here is a video:
https://github.com/user-attachments/assets/827db575-5d0c-497d-a655-60c3829d9797

I can turn WiFi or Bluetooth on and off, but I cannot se the change.
In the app it's displayed correctly.

Are logs necessary and how could I provide logs?

**Comment by CasperVerswijvelt** [comment]
No need for logs, I was able to reproduce it on a simulator just now
I'll need to do some further debugging

**Comment by CasperVerswijvelt** [comment]
Hmm, when I'm calling [requestListeningState](https://developer.android.com/reference/android/service/quicksettings/TileService#requestListeningState(android.content.Context,%20android.content.ComponentName)), it only actually puts the given tile in a listening state if that tile hasn't been clicked since the app was started

**Comment by CookieXD** [comment]
I don't understand what your trying to tell me. 
However your going to try and fix it soon with an Update, correct?

I will be more than happy if you manage to fix it 😁

(Can I donate to you for your amazing work BTW?)

**Comment by CasperVerswijvelt** [comment]
My current assumption is that this is an Android bug, so I'll probably be reporting that to their issue tracker.

You can sponsor this project via this link: [ko-fi.com/casperverswijvelt](https://ko-fi.com/casperverswijvelt) :)

**Comment by CasperVerswijvelt** [comment]
Link to Android bug report: https://issuetracker.google.com/issues/357257407

**Comment by CasperVerswijvelt** [comment]
Google closed my upstream issue without giving much more info, but I looked into this again and saw that after clicking a tile, it would stay in listening state until the QS is closed, when earlier android versions would only swiftly enter listening state. Due to the BIT app not correctly keeping the tile up to date during listening state but (only doing so when entering listening state), it gave the result as described in earlier comments.

Commit [c64d39d](https://github.com/CasperVerswijvelt/Better-Internet-Tiles/commit/c64d39d510e3daf07634509a604f47069180aa52) should fix this

**Comment by CasperVerswijvelt** [comment]
Available in release [v3.1.0 beta](https://github.com/CasperVerswijvelt/Better-Internet-Tiles/releases/tag/v3.1.0-beta)

If anyone else could verify the fix, that would be great

**Comment by leifalbor** [comment]
Just installed on Android 15 QPR1 Beta 2 (AP41.240823.009) and can confirm toggles for Bluetooth and wifi tiles work as intended.

**Comment by CookieXD** [comment]
For me too. Works again
